apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f docker-compose.yaml
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: centos3
  name: centos3
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: centos3
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f docker-compose.yaml
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.network/diveintoansiblelabmaster_diveinto.io: "true"
        io.kompose.service: centos3
    spec:
      containers:
      - image: spurin/diveintoansible:centos
        imagePullPolicy: ""
        name: centos3
        ports:
        - containerPort: 22
        - containerPort: 7681
        resources: {}
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /config
          name: centos3-claim0
        - mountPath: /shared
          name: centos3-claim1
        - mountPath: /home/ansible
          name: centos3-claim2
        - mountPath: /root
          name: centos3-claim3
      hostname: centos3
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: centos3-claim0
        persistentVolumeClaim:
          claimName: centos3-claim0
      - name: centos3-claim1
        persistentVolumeClaim:
          claimName: centos3-claim1
      - name: centos3-claim2
        persistentVolumeClaim:
          claimName: centos3-claim2
      - name: centos3-claim3
        persistentVolumeClaim:
          claimName: centos3-claim3
status: {}
