apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f docker-compose.yaml
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: centos3
  name: centos3
spec:
  ports:
  - name: "2227"
    port: 2227
    targetPort: 22
  - name: "7687"
    port: 7687
    targetPort: 7681
  selector:
    io.kompose.service: centos3
status:
  loadBalancer: {}
