apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f docker-compose.yaml
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: ubuntu1
  name: ubuntu1
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: ubuntu1
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f docker-compose.yaml
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.network/diveintoansiblelabmaster_diveinto.io: "true"
        io.kompose.service: ubuntu1
    spec:
      containers:
      - image: spurin/diveintoansible:ubuntu
        imagePullPolicy: ""
        name: ubuntu1
        ports:
        - containerPort: 22
        - containerPort: 7681
        resources: {}
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /config
          name: ubuntu1-claim0
        - mountPath: /shared
          name: ubuntu1-claim1
        - mountPath: /home/ansible
          name: ubuntu1-claim2
        - mountPath: /root
          name: ubuntu1-claim3
      hostname: ubuntu1
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: ubuntu1-claim0
        persistentVolumeClaim:
          claimName: ubuntu1-claim0
      - name: ubuntu1-claim1
        persistentVolumeClaim:
          claimName: ubuntu1-claim1
      - name: ubuntu1-claim2
        persistentVolumeClaim:
          claimName: ubuntu1-claim2
      - name: ubuntu1-claim3
        persistentVolumeClaim:
          claimName: ubuntu1-claim3
status: {}
