apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f docker-compose.yaml
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: ubuntu2
  name: ubuntu2
spec:
  ports:
  - name: "2223"
    port: 2223
    targetPort: 22
  - name: "7683"
    port: 7683
    targetPort: 7681
  selector:
    io.kompose.service: ubuntu2
status:
  loadBalancer: {}
