apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f docker-compose.yaml
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: ubuntu-c
  name: ubuntu-c
spec:
  ports:
  - name: "2221"
    port: 2221
    targetPort: 22
  - name: "7681"
    port: 7681
    targetPort: 7681
  selector:
    io.kompose.service: ubuntu-c
status:
  loadBalancer: {}
