apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f docker-compose.yaml
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: ubuntu3
  name: ubuntu3
spec:
  ports:
  - name: "2224"
    port: 2224
    targetPort: 22
  - name: "7684"
    port: 7684
    targetPort: 7681
  selector:
    io.kompose.service: ubuntu3
status:
  loadBalancer: {}
